INSERT INTO pays VALUES (1,'AF','Afghanistan','Afghanistan');
INSERT INTO pays VALUES (2,'ZA','Afrique du Sud','South Africa');
INSERT INTO pays VALUES (3,'AL','Albanie','Albania');
INSERT INTO pays VALUES (4,'DZ','Algérie','Algeria');
INSERT INTO pays VALUES (5,'DE','Allemagne','Germany');
INSERT INTO pays VALUES (6,'AD','Andorre','Andorra');
INSERT INTO pays VALUES (7,'AO','Angola','Angola');
INSERT INTO pays VALUES (8,'AI','Anguilla','Anguilla');
INSERT INTO pays VALUES (9,'AQ','Antarctique','Antarctica');
INSERT INTO pays VALUES (10,'AG','Antigua-et-Barbuda','Antigua & Barbuda');
INSERT INTO pays VALUES (11,'AN','Antilles néerlandaises','Netherlands Antilles');
INSERT INTO pays VALUES (12,'SA','Arabie saoudite','Saudi Arabia');
INSERT INTO pays VALUES (13,'AR','Argentine','Argentina');
INSERT INTO pays VALUES (14,'AM','Arménie','Armenia');
INSERT INTO pays VALUES (15,'AW','Aruba','Aruba');
INSERT INTO pays VALUES (16,'AU','Australie','Australia');
INSERT INTO pays VALUES (17,'AT','Autriche','Austria');
INSERT INTO pays VALUES (18,'AZ','Azerbaïdjan','Azerbaijan');
INSERT INTO pays VALUES (19,'BJ','Bénin','Benin');
INSERT INTO pays VALUES (20,'BS','Bahamas','Bahamas, The');
INSERT INTO pays VALUES (21,'BH','Bahreïn','Bahrain');
INSERT INTO pays VALUES (22,'BD','Bangladesh','Bangladesh');
INSERT INTO pays VALUES (23,'BB','Barbade','Barbados');
INSERT INTO pays VALUES (24,'PW','Belau','Palau');
INSERT INTO pays VALUES (25,'BE','Belgique','Belgium');
INSERT INTO pays VALUES (26,'BZ','Belize','Belize');
INSERT INTO pays VALUES (27,'BM','Bermudes','Bermuda');
INSERT INTO pays VALUES (28,'BT','Bhoutan','Bhutan');
INSERT INTO pays VALUES (29,'BY','Biélorussie','Belarus');
INSERT INTO pays VALUES (30,'MM','Birmanie','Myanmar (ex-Burma)');
INSERT INTO pays VALUES (31,'BO','Bolivie','Bolivia');
INSERT INTO pays VALUES (32,'BA','Bosnie-Herzégovine','Bosnia and Herzegovina');
INSERT INTO pays VALUES (33,'BW','Botswana','Botswana');
INSERT INTO pays VALUES (34,'BR','Brésil','Brazil');
INSERT INTO pays VALUES (35,'BN','Brunei','Brunei Darussalam');
INSERT INTO pays VALUES (36,'BG','Bulgarie','Bulgaria');
INSERT INTO pays VALUES (37,'BF','Burkina Faso','Burkina Faso');
INSERT INTO pays VALUES (38,'BI','Burundi','Burundi');
INSERT INTO pays VALUES (39,'CI','Côte d\'Ivoire','Ivory Coast (see Cote d\'Ivoire)');
INSERT INTO pays VALUES (40,'KH','Cambodge','Cambodia');
INSERT INTO pays VALUES (41,'CM','Cameroun','Cameroon');
INSERT INTO pays VALUES (42,'CA','Canada','Canada');
INSERT INTO pays VALUES (43,'CV','Cap-Vert','Cape Verde');
INSERT INTO pays VALUES (44,'CL','Chili','Chile');
INSERT INTO pays VALUES (45,'CN','Chine','China');
INSERT INTO pays VALUES (46,'CY','Chypre','Cyprus');
INSERT INTO pays VALUES (47,'CO','Colombie','Colombia');
INSERT INTO pays VALUES (48,'KM','Comores','Comoros');
INSERT INTO pays VALUES (49,'CG','Congo','Congo');
INSERT INTO pays VALUES (50,'KP','Corée du Nord','Korea, Demo. People\'s Rep. of');
INSERT INTO pays VALUES (51,'KR','Corée du Sud','Korea, (South) Republic of');
INSERT INTO pays VALUES (52,'CR','Costa Rica','Costa Rica');
INSERT INTO pays VALUES (53,'HR','Croatie','Croatia');
INSERT INTO pays VALUES (54,'CU','Cuba','Cuba');
INSERT INTO pays VALUES (55,'DK','Danemark','Denmark');
INSERT INTO pays VALUES (56,'DJ','Djibouti','Djibouti');
INSERT INTO pays VALUES (57,'DM','Dominique','Dominica');
INSERT INTO pays VALUES (58,'EG','Égypte','Egypt');
INSERT INTO pays VALUES (59,'AE','Émirats arabes unis','United Arab Emirates');
INSERT INTO pays VALUES (60,'EC','Équateur','Ecuador');
INSERT INTO pays VALUES (61,'ER','Érythrée','Eritrea');
INSERT INTO pays VALUES (62,'ES','Espagne','Spain');
INSERT INTO pays VALUES (63,'EE','Estonie','Estonia');
INSERT INTO pays VALUES (64,'US','États-Unis','United States');
INSERT INTO pays VALUES (65,'ET','Éthiopie','Ethiopia');
INSERT INTO pays VALUES (66,'FI','Finlande','Finland');
INSERT INTO pays VALUES (67,'FR','France','France');
INSERT INTO pays VALUES (68,'GE','Géorgie','Georgia');
INSERT INTO pays VALUES (69,'GA','Gabon','Gabon');
INSERT INTO pays VALUES (70,'GM','Gambie','Gambia, the');
INSERT INTO pays VALUES (71,'GH','Ghana','Ghana');
INSERT INTO pays VALUES (72,'GI','Gibraltar','Gibraltar');
INSERT INTO pays VALUES (73,'GR','Grèce','Greece');
INSERT INTO pays VALUES (74,'GD','Grenade','Grenada');
INSERT INTO pays VALUES (75,'GL','Groenland','Greenland');
INSERT INTO pays VALUES (76,'GP','Guadeloupe','Guinea, Equatorial');
INSERT INTO pays VALUES (77,'GU','Guam','Guam');
INSERT INTO pays VALUES (78,'GT','Guatemala','Guatemala');
INSERT INTO pays VALUES (79,'GN','Guinée','Guinea');
INSERT INTO pays VALUES (80,'GQ','Guinée équatoriale','Equatorial Guinea');
INSERT INTO pays VALUES (81,'GW','Guinée-Bissao','Guinea-Bissau');
INSERT INTO pays VALUES (82,'GY','Guyana','Guyana');
INSERT INTO pays VALUES (83,'GF','Guyane française','Guiana, French');
INSERT INTO pays VALUES (84,'HT','Haïti','Haiti');
INSERT INTO pays VALUES (85,'HN','Honduras','Honduras');
INSERT INTO pays VALUES (86,'HK','Hong Kong','Hong Kong, (China)');
INSERT INTO pays VALUES (87,'HU','Hongrie','Hungary');
INSERT INTO pays VALUES (88,'BV','Ile Bouvet','Bouvet Island');
INSERT INTO pays VALUES (89,'CX','Ile Christmas','Christmas Island');
INSERT INTO pays VALUES (90,'NF','Ile Norfolk','Norfolk Island');
INSERT INTO pays VALUES (91,'KY','Iles Cayman','Cayman Islands');
INSERT INTO pays VALUES (92,'CK','Iles Cook','Cook Islands');
INSERT INTO pays VALUES (93,'FO','Iles Féroé','Faroe Islands');
INSERT INTO pays VALUES (94,'FK','Iles Falkland','Falkland Islands (Malvinas)');
INSERT INTO pays VALUES (95,'FJ','Iles Fidji','Fiji');
INSERT INTO pays VALUES (96,'GS','Iles Géorgie du Sud et Sandwich du Sud','S. Georgia and S. Sandwich Is.');
INSERT INTO pays VALUES (97,'HM','Iles Heard et McDonald','Heard and McDonald Islands');
INSERT INTO pays VALUES (98,'MH','Iles Marshall','Marshall Islands');
INSERT INTO pays VALUES (99,'PN','Iles Pitcairn','Pitcairn Island');
INSERT INTO pays VALUES (100,'SB','Iles Salomon','Solomon Islands');
INSERT INTO pays VALUES (101,'SJ','Iles Svalbard et Jan Mayen','Svalbard and Jan Mayen Islands');
INSERT INTO pays VALUES (102,'TC','Iles Turks-et-Caicos','Turks and Caicos Islands');
INSERT INTO pays VALUES (103,'VI','Iles Vierges américaines','Virgin Islands, U.S.');
INSERT INTO pays VALUES (104,'VG','Iles Vierges britanniques','Virgin Islands, British');
INSERT INTO pays VALUES (105,'CC','Iles des Cocos (Keeling)','Cocos (Keeling) Islands');
INSERT INTO pays VALUES (106,'UM','Iles mineures éloignées des États-Unis','US Minor Outlying Islands');
INSERT INTO pays VALUES (107,'IN','Inde','India');
INSERT INTO pays VALUES (108,'ID','Indonésie','Indonesia');
INSERT INTO pays VALUES (109,'IR','Iran','Iran, Islamic Republic of');
INSERT INTO pays VALUES (110,'IQ','Iraq','Iraq');
INSERT INTO pays VALUES (111,'IE','Irlande','Ireland');
INSERT INTO pays VALUES (112,'IS','Islande','Iceland');
INSERT INTO pays VALUES (113,'IL','IsraÃ«l','Israel');
INSERT INTO pays VALUES (114,'IT','Italie','Italy');
INSERT INTO pays VALUES (115,'JM','Jamaïque','Jamaica');
INSERT INTO pays VALUES (116,'JP','Japon','Japan');
INSERT INTO pays VALUES (117,'JO','Jordanie','Jordan');
INSERT INTO pays VALUES (118,'KZ','Kazakhstan','Kazakhstan');
INSERT INTO pays VALUES (119,'KE','Kenya','Kenya');
INSERT INTO pays VALUES (120,'KG','Kirghizistan','Kyrgyzstan');
INSERT INTO pays VALUES (121,'KI','Kiribati','Kiribati');
INSERT INTO pays VALUES (122,'KW','Koweït','Kuwait');
INSERT INTO pays VALUES (123,'LA','Laos','Lao People\'s Democratic Republic');
INSERT INTO pays VALUES (124,'LS','Lesotho','Lesotho');
INSERT INTO pays VALUES (125,'LV','Lettonie','Latvia');
INSERT INTO pays VALUES (126,'LB','Liban','Lebanon');
INSERT INTO pays VALUES (127,'LR','Liberia','Liberia');
INSERT INTO pays VALUES (128,'LY','Libye','Libyan Arab Jamahiriya');
INSERT INTO pays VALUES (129,'LI','Liechtenstein','Liechtenstein');
INSERT INTO pays VALUES (130,'LT','Lituanie','Lithuania');
INSERT INTO pays VALUES (131,'LU','Luxembourg','Luxembourg');
INSERT INTO pays VALUES (132,'MO','Macao','Macao, (China)');
INSERT INTO pays VALUES (133,'MG','Madagascar','Madagascar');
INSERT INTO pays VALUES (134,'MY','Malaisie','Malaysia');
INSERT INTO pays VALUES (135,'MW','Malawi','Malawi');
INSERT INTO pays VALUES (136,'MV','Maldives','Maldives');
INSERT INTO pays VALUES (137,'ML','Mali','Mali');
INSERT INTO pays VALUES (138,'MT','Malte','Malta');
INSERT INTO pays VALUES (139,'MP','Mariannes du Nord','Northern Mariana Islands');
INSERT INTO pays VALUES (140,'MA','Maroc','Morocco');
INSERT INTO pays VALUES (141,'MQ','Martinique','Martinique');
INSERT INTO pays VALUES (142,'MU','Maurice','Mauritius');
INSERT INTO pays VALUES (143,'MR','Mauritanie','Mauritania');
INSERT INTO pays VALUES (144,'YT','Mayotte','Mayotte');
INSERT INTO pays VALUES (145,'MX','Mexique','Mexico');
INSERT INTO pays VALUES (146,'FM','Micronésie','Micronesia, Federated States of');
INSERT INTO pays VALUES (147,'MD','Moldavie','Moldova, Republic of');
INSERT INTO pays VALUES (148,'MC','Monaco','Monaco');
INSERT INTO pays VALUES (149,'MN','Mongolie','Mongolia');
INSERT INTO pays VALUES (150,'MS','Montserrat','Montserrat');
INSERT INTO pays VALUES (151,'MZ','Mozambique','Mozambique');
INSERT INTO pays VALUES (152,'NP','Népal','Nepal');
INSERT INTO pays VALUES (153,'NA','Namibie','Namibia');
INSERT INTO pays VALUES (154,'NR','Nauru','Nauru');
INSERT INTO pays VALUES (155,'NI','Nicaragua','Nicaragua');
INSERT INTO pays VALUES (156,'NE','Niger','Niger');
INSERT INTO pays VALUES (157,'NG','Nigeria','Nigeria');
INSERT INTO pays VALUES (158,'NU','Nioué','Niue');
INSERT INTO pays VALUES (159,'NO','Norvège','Norway');
INSERT INTO pays VALUES (160,'NC','Nouvelle-Calédonie','New Caledonia');
INSERT INTO pays VALUES (161,'NZ','Nouvelle-Zélande','New Zealand');
INSERT INTO pays VALUES (162,'OM','Oman','Oman');
INSERT INTO pays VALUES (163,'UG','Ouganda','Uganda');
INSERT INTO pays VALUES (164,'UZ','Ouzbékistan','Uzbekistan');
INSERT INTO pays VALUES (165,'PE','Pérou','Peru');
INSERT INTO pays VALUES (166,'PK','Pakistan','Pakistan');
INSERT INTO pays VALUES (167,'PA','Panama','Panama');
INSERT INTO pays VALUES (168,'PG','Papouasie-Nouvelle-Guinée','Papua New Guinea');
INSERT INTO pays VALUES (169,'PY','Paraguay','Paraguay');
INSERT INTO pays VALUES (170,'NL','Pays-Bas','Netherlands');
INSERT INTO pays VALUES (171,'PH','Philippines','Philippines');
INSERT INTO pays VALUES (172,'PL','Pologne','Poland');
INSERT INTO pays VALUES (173,'PF','Polynésie française','French Polynesia');
INSERT INTO pays VALUES (174,'PR','Porto Rico','Puerto Rico');
INSERT INTO pays VALUES (175,'PT','Portugal','Portugal');
INSERT INTO pays VALUES (176,'QA','Qatar','Qatar');
INSERT INTO pays VALUES (177,'CF','République centrafricaine','Central African Republic');
INSERT INTO pays VALUES (178,'CD','République démocratique du Congo','Congo, Democratic Rep. of the');
INSERT INTO pays VALUES (179,'DO','République dominicaine','Dominican Republic');
INSERT INTO pays VALUES (180,'CZ','République tchèque','Czech Republic');
INSERT INTO pays VALUES (181,'RE','Réunion','Reunion');
INSERT INTO pays VALUES (182,'RO','Roumanie','Romania');
INSERT INTO pays VALUES (183,'GB','Royaume-Uni','Saint Pierre and Miquelon');
INSERT INTO pays VALUES (184,'RU','Russie','Russia (Russian Federation)');
INSERT INTO pays VALUES (185,'RW','Rwanda','Rwanda');
INSERT INTO pays VALUES (186,'SN','Sénégal','Senegal');
INSERT INTO pays VALUES (187,'EH','Sahara occidental','Western Sahara');
INSERT INTO pays VALUES (188,'KN','Saint-Christophe-et-Niévès','Saint Kitts and Nevis');
INSERT INTO pays VALUES (189,'SM','Saint-Marin','San Marino');
INSERT INTO pays VALUES (190,'PM','Saint-Pierre-et-Miquelon','Saint Pierre and Miquelon');
INSERT INTO pays VALUES (191,'VA','Saint-Siège ','Vatican City State (Holy See)');
INSERT INTO pays VALUES (192,'VC','Saint-Vincent-et-les-Grenadines','Saint Vincent and the Grenadines');
INSERT INTO pays VALUES (193,'SH','Sainte-Hélène','Saint Helena');
INSERT INTO pays VALUES (194,'LC','Sainte-Lucie','Saint Lucia');
INSERT INTO pays VALUES (195,'SV','Salvador','El Salvador');
INSERT INTO pays VALUES (196,'WS','Samoa','Samoa');
INSERT INTO pays VALUES (197,'AS','Samoa américaines','American Samoa');
INSERT INTO pays VALUES (198,'ST','Sao Tomé-et-Principe','Sao Tome and Principe');
INSERT INTO pays VALUES (199,'SC','Seychelles','Seychelles');
INSERT INTO pays VALUES (200,'SL','Sierra Leone','Sierra Leone');
INSERT INTO pays VALUES (201,'SG','Singapour','Singapore');
INSERT INTO pays VALUES (202,'SI','Slovénie','Slovenia');
INSERT INTO pays VALUES (203,'SK','Slovaquie','Slovakia');
INSERT INTO pays VALUES (204,'SO','Somalie','Somalia');
INSERT INTO pays VALUES (205,'SD','Soudan','Sudan');
INSERT INTO pays VALUES (206,'LK','Sri Lanka','Sri Lanka (ex-Ceilan)');
INSERT INTO pays VALUES (207,'SE','Suède','Sweden');
INSERT INTO pays VALUES (208,'CH','Suisse','Switzerland');
INSERT INTO pays VALUES (209,'SR','Suriname','Suriname');
INSERT INTO pays VALUES (210,'SZ','Swaziland','Swaziland');
INSERT INTO pays VALUES (211,'SY','Syrie','Syrian Arab Republic');
INSERT INTO pays VALUES (212,'TW','Taïwan','Taiwan');
INSERT INTO pays VALUES (213,'TJ','Tadjikistan','Tajikistan');
INSERT INTO pays VALUES (214,'TZ','Tanzanie','Tanzania, United Republic of');
INSERT INTO pays VALUES (215,'TD','Tchad','Chad');
INSERT INTO pays VALUES (216,'TF','Terres australes françaises','French Southern Territories - TF');
INSERT INTO pays VALUES (217,'IO','Territoire britannique de l\'Océan Indien','British Indian Ocean Territory');
INSERT INTO pays VALUES (218,'TH','Thaïlande','Thailand');
INSERT INTO pays VALUES (219,'TL','Timor Oriental','Timor-Leste (East Timor)');
INSERT INTO pays VALUES (220,'TG','Togo','Togo');
INSERT INTO pays VALUES (221,'TK','Tokélaou','Tokelau');
INSERT INTO pays VALUES (222,'TO','Tonga','Tonga');
INSERT INTO pays VALUES (223,'TT','Trinité-et-Tobago','Trinidad & Tobago');
INSERT INTO pays VALUES (224,'TN','Tunisie','Tunisia');
INSERT INTO pays VALUES (225,'TM','Turkménistan','Turkmenistan');
INSERT INTO pays VALUES (226,'TR','Turquie','Turkey');
INSERT INTO pays VALUES (227,'TV','Tuvalu','Tuvalu');
INSERT INTO pays VALUES (228,'UA','Ukraine','Ukraine');
INSERT INTO pays VALUES (229,'UY','Uruguay','Uruguay');
INSERT INTO pays VALUES (230,'VU','Vanuatu','Vanuatu');
INSERT INTO pays VALUES (231,'VE','Venezuela','Venezuela');
INSERT INTO pays VALUES (232,'VN','Viêt Nam','Viet Nam');
INSERT INTO pays VALUES (233,'WF','Wallis-et-Futuna','Wallis and Futuna');
INSERT INTO pays VALUES (234,'YE','Yémen','Yemen');
INSERT INTO pays VALUES (235,'YU','Yougoslavie','Saint Pierre and Miquelon');
INSERT INTO pays VALUES (236,'ZM','Zambie','Zambia');
INSERT INTO pays VALUES (237,'ZW','Zimbabwe','Zimbabwe');
INSERT INTO pays VALUES (238,'MK','ex-République yougoslave de Macédoine','Macedonia, TFYR');

/*INSERT INTO menus VALUES(1, NULL, 1, 22, 'Intranet', '');*/