DROP TABLE IF EXISTS pays;
CREATE TABLE pays (
    id INT NOT NULL AUTO_INCREMENT,
    actif BOOLEAN NOT NULL DEFAULT true,
    code VARCHAR(2) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    nom_en VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;