DROP TABLE IF EXISTS pays;
CREATE TABLE pays (
    id INT NOT NULL AUTO_INCREMENT,
    actif BOOLEAN NOT NULL DEFAULT true,
    code VARCHAR(2) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    nom_en VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (1, '1', 'AF', 'Afghanistan', 'Afghanistan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (2, '1', 'ZA', 'Afrique du Sud', 'South Africa');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (3, '1', 'AL', 'Albanie', 'Albania');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (4, '1', 'DZ', 'Algérie', 'Algeria');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (5, '1', 'DE', 'Allemagne', 'Germany');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (6, '1', 'AD', 'Andorre', 'Andorra');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (7, '1', 'AO', 'Angola', 'Angola');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (8, '1', 'AI', 'Anguilla', 'Anguilla');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (9, '1', 'AQ', 'Antarctique', 'Antarctica');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (10, '1', 'AG', 'Antigua-et-Barbuda', 'Antigua & Barbuda');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (11, '1', 'AN', 'Antilles néerlandaises', 'Netherlands Antilles');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (12, '1', 'SA', 'Arabie saoudite', 'Saudi Arabia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (13, '1', 'AR', 'Argentine', 'Argentina');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (14, '1', 'AM', 'Arménie', 'Armenia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (15, '1', 'AW', 'Aruba', 'Aruba');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (16, '1', 'AU', 'Australie', 'Australia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (17, '1', 'AT', 'Autriche', 'Austria');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (18, '1', 'AZ', 'Azerbaïdjan', 'Azerbaijan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (19, '1', 'BJ', 'Bénin', 'Benin');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (20, '1', 'BS', 'Bahamas', 'Bahamas, The');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (21, '1', 'BH', 'Bahreïn', 'Bahrain');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (22, '1', 'BD', 'Bangladesh', 'Bangladesh');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (23, '1', 'BB', 'Barbade', 'Barbados');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (24, '1', 'PW', 'Belau', 'Palau');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (25, '1', 'BE', 'Belgique', 'Belgium');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (26, '1', 'BZ', 'Belize', 'Belize');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (27, '1', 'BM', 'Bermudes', 'Bermuda');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (28, '1', 'BT', 'Bhoutan', 'Bhutan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (29, '1', 'BY', 'Biélorussie', 'Belarus');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (30, '1', 'MM', 'Birmanie', 'Myanmar (ex-Burma)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (31, '1', 'BO', 'Bolivie', 'Bolivia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (32, '1', 'BA', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (33, '1', 'BW', 'Botswana', 'Botswana');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (34, '1', 'BR', 'Brésil', 'Brazil');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (35, '1', 'BN', 'Brunei', 'Brunei Darussalam');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (36, '1', 'BG', 'Bulgarie', 'Bulgaria');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (37, '1', 'BF', 'Burkina Faso', 'Burkina Faso');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (38, '1', 'BI', 'Burundi', 'Burundi');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (39, '1', 'CI', 'Côte d''Ivoire', 'Ivory Coast (see Cote d''Ivoire)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (40, '1', 'KH', 'Cambodge', 'Cambodia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (41, '1', 'CM', 'Cameroun', 'Cameroon');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (42, '1', 'CA', 'Canada', 'Canada');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (43, '1', 'CV', 'Cap-Vert', 'Cape Verde');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (44, '1', 'CL', 'Chili', 'Chile');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (45, '1', 'CN', 'Chine', 'China');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (46, '1', 'CY', 'Chypre', 'Cyprus');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (47, '1', 'CO', 'Colombie', 'Colombia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (48, '1', 'KM', 'Comores', 'Comoros');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (49, '1', 'CG', 'Congo', 'Congo');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (50, '1', 'KP', 'Corée du Nord', 'Korea, Demo. People''s Rep. of');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (51, '1', 'KR', 'Corée du Sud', 'Korea, (South) Republic of');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (52, '1', 'CR', 'Costa Rica', 'Costa Rica');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (53, '1', 'HR', 'Croatie', 'Croatia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (54, '1', 'CU', 'Cuba', 'Cuba');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (55, '1', 'DK', 'Danemark', 'Denmark');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (56, '1', 'DJ', 'Djibouti', 'Djibouti');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (57, '1', 'DM', 'Dominique', 'Dominica');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (58, '1', 'EG', 'Égypte', 'Egypt');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (59, '1', 'AE', 'Émirats arabes unis', 'United Arab Emirates');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (60, '1', 'EC', 'Équateur', 'Ecuador');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (61, '1', 'ER', 'Érythrée', 'Eritrea');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (62, '1', 'ES', 'Espagne', 'Spain');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (63, '1', 'EE', 'Estonie', 'Estonia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (64, '1', 'US', 'États-Unis', 'United States');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (65, '1', 'ET', 'Éthiopie', 'Ethiopia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (66, '1', 'FI', 'Finlande', 'Finland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (67, '1', 'FR', 'France', 'France');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (68, '1', 'GE', 'Géorgie', 'Georgia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (69, '1', 'GA', 'Gabon', 'Gabon');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (70, '1', 'GM', 'Gambie', 'Gambia, the');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (71, '1', 'GH', 'Ghana', 'Ghana');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (72, '1', 'GI', 'Gibraltar', 'Gibraltar');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (73, '1', 'GR', 'Grèce', 'Greece');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (74, '1', 'GD', 'Grenade', 'Grenada');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (75, '1', 'GL', 'Groenland', 'Greenland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (76, '1', 'GP', 'Guadeloupe', 'Guinea, Equatorial');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (77, '1', 'GU', 'Guam', 'Guam');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (78, '1', 'GT', 'Guatemala', 'Guatemala');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (79, '1', 'GN', 'Guinée', 'Guinea');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (80, '1', 'GQ', 'Guinée équatoriale', 'Equatorial Guinea');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (81, '1', 'GW', 'Guinée-Bissao', 'Guinea-Bissau');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (82, '1', 'GY', 'Guyana', 'Guyana');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (83, '1', 'GF', 'Guyane française', 'Guiana, French');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (84, '1', 'HT', 'Haïti', 'Haiti');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (85, '1', 'HN', 'Honduras', 'Honduras');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (86, '1', 'HK', 'Hong Kong', 'Hong Kong, (China)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (87, '1', 'HU', 'Hongrie', 'Hungary');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (88, '1', 'BV', 'Ile Bouvet', 'Bouvet Island');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (89, '1', 'CX', 'Ile Christmas', 'Christmas Island');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (90, '1', 'NF', 'Ile Norfolk', 'Norfolk Island');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (91, '1', 'KY', 'Iles Cayman', 'Cayman Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (92, '1', 'CK', 'Iles Cook', 'Cook Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (93, '1', 'FO', 'Iles Féroé', 'Faroe Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (94, '1', 'FK', 'Iles Falkland', 'Falkland Islands (Malvinas)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (95, '1', 'FJ', 'Iles Fidji', 'Fiji');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (96, '1', 'GS', 'Iles Géorgie du Sud et Sandwich du Sud', 'S. Georgia and S. Sandwich Is.');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (97, '1', 'HM', 'Iles Heard et McDonald', 'Heard and McDonald Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (98, '1', 'MH', 'Iles Marshall', 'Marshall Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (99, '1', 'PN', 'Iles Pitcairn', 'Pitcairn Island');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (100, '1', 'SB', 'Iles Salomon', 'Solomon Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (101, '1', 'SJ', 'Iles Svalbard et Jan Mayen', 'Svalbard and Jan Mayen Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (102, '1', 'TC', 'Iles Turks-et-Caicos', 'Turks and Caicos Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (103, '1', 'VI', 'Iles Vierges américaines', 'Virgin Islands, U.S.');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (104, '1', 'VG', 'Iles Vierges britanniques', 'Virgin Islands, British');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (105, '1', 'CC', 'Iles des Cocos (Keeling)', 'Cocos (Keeling) Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (106, '1', 'UM', 'Iles mineures éloignées des États-Unis', 'US Minor Outlying Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (107, '1', 'IN', 'Inde', 'India');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (108, '1', 'ID', 'Indonésie', 'Indonesia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (109, '1', 'IR', 'Iran', 'Iran, Islamic Republic of');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (110, '1', 'IQ', 'Iraq', 'Iraq');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (111, '1', 'IE', 'Irlande', 'Ireland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (112, '1', 'IS', 'Islande', 'Iceland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (113, '1', 'IL', 'IsraÃ«l', 'Israel');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (114, '1', 'IT', 'Italie', 'Italy');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (115, '1', 'JM', 'Jamaïque', 'Jamaica');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (116, '1', 'JP', 'Japon', 'Japan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (117, '1', 'JO', 'Jordanie', 'Jordan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (118, '1', 'KZ', 'Kazakhstan', 'Kazakhstan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (119, '1', 'KE', 'Kenya', 'Kenya');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (120, '1', 'KG', 'Kirghizistan', 'Kyrgyzstan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (121, '1', 'KI', 'Kiribati', 'Kiribati');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (122, '1', 'KW', 'Koweït', 'Kuwait');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (123, '1', 'LA', 'Laos', 'Lao People''s Democratic Republic');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (124, '1', 'LS', 'Lesotho', 'Lesotho');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (125, '1', 'LV', 'Lettonie', 'Latvia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (126, '1', 'LB', 'Liban', 'Lebanon');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (127, '1', 'LR', 'Liberia', 'Liberia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (128, '1', 'LY', 'Libye', 'Libyan Arab Jamahiriya');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (129, '1', 'LI', 'Liechtenstein', 'Liechtenstein');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (130, '1', 'LT', 'Lituanie', 'Lithuania');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (131, '1', 'LU', 'Luxembourg', 'Luxembourg');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (132, '1', 'MO', 'Macao', 'Macao, (China)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (133, '1', 'MG', 'Madagascar', 'Madagascar');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (134, '1', 'MY', 'Malaisie', 'Malaysia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (135, '1', 'MW', 'Malawi', 'Malawi');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (136, '1', 'MV', 'Maldives', 'Maldives');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (137, '1', 'ML', 'Mali', 'Mali');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (138, '1', 'MT', 'Malte', 'Malta');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (139, '1', 'MP', 'Mariannes du Nord', 'Northern Mariana Islands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (140, '1', 'MA', 'Maroc', 'Morocco');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (141, '1', 'MQ', 'Martinique', 'Martinique');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (142, '1', 'MU', 'Maurice', 'Mauritius');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (143, '1', 'MR', 'Mauritanie', 'Mauritania');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (144, '1', 'YT', 'Mayotte', 'Mayotte');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (145, '1', 'MX', 'Mexique', 'Mexico');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (146, '1', 'FM', 'Micronésie', 'Micronesia, Federated States of');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (147, '1', 'MD', 'Moldavie', 'Moldova, Republic of');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (148, '1', 'MC', 'Monaco', 'Monaco');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (149, '1', 'MN', 'Mongolie', 'Mongolia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (150, '1', 'MS', 'Montserrat', 'Montserrat');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (151, '1', 'MZ', 'Mozambique', 'Mozambique');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (152, '1', 'NP', 'Népal', 'Nepal');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (153, '1', 'NA', 'Namibie', 'Namibia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (154, '1', 'NR', 'Nauru', 'Nauru');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (155, '1', 'NI', 'Nicaragua', 'Nicaragua');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (156, '1', 'NE', 'Niger', 'Niger');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (157, '1', 'NG', 'Nigeria', 'Nigeria');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (158, '1', 'NU', 'Nioué', 'Niue');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (159, '1', 'NO', 'Norvège', 'Norway');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (160, '1', 'NC', 'Nouvelle-Calédonie', 'New Caledonia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (161, '1', 'NZ', 'Nouvelle-Zélande', 'New Zealand');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (162, '1', 'OM', 'Oman', 'Oman');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (163, '1', 'UG', 'Ouganda', 'Uganda');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (164, '1', 'UZ', 'Ouzbékistan', 'Uzbekistan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (165, '1', 'PE', 'Pérou', 'Peru');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (166, '1', 'PK', 'Pakistan', 'Pakistan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (167, '1', 'PA', 'Panama', 'Panama');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (168, '1', 'PG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (169, '1', 'PY', 'Paraguay', 'Paraguay');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (170, '1', 'NL', 'Pays-Bas', 'Netherlands');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (171, '1', 'PH', 'Philippines', 'Philippines');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (172, '1', 'PL', 'Pologne', 'Poland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (173, '1', 'PF', 'Polynésie française', 'French Polynesia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (174, '1', 'PR', 'Porto Rico', 'Puerto Rico');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (175, '1', 'PT', 'Portugal', 'Portugal');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (176, '1', 'QA', 'Qatar', 'Qatar');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (177, '1', 'CF', 'République centrafricaine', 'Central African Republic');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (178, '1', 'CD', 'République démocratique du Congo', 'Congo, Democratic Rep. of the');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (179, '1', 'DO', 'République dominicaine', 'Dominican Republic');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (180, '1', 'CZ', 'République tchèque', 'Czech Republic');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (181, '1', 'RE', 'Réunion', 'Reunion');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (182, '1', 'RO', 'Roumanie', 'Romania');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (183, '1', 'GB', 'Royaume-Uni', 'Saint Pierre and Miquelon');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (184, '1', 'RU', 'Russie', 'Russia (Russian Federation)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (185, '1', 'RW', 'Rwanda', 'Rwanda');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (186, '1', 'SN', 'Sénégal', 'Senegal');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (187, '1', 'EH', 'Sahara occidental', 'Western Sahara');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (188, '1', 'KN', 'Saint-Christophe-et-Niévès', 'Saint Kitts and Nevis');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (189, '1', 'SM', 'Saint-Marin', 'San Marino');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (190, '1', 'PM', 'Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (191, '1', 'VA', 'Saint-Siège ', 'Vatican City State (Holy See)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (192, '1', 'VC', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (193, '1', 'SH', 'Sainte-Hélène', 'Saint Helena');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (194, '1', 'LC', 'Sainte-Lucie', 'Saint Lucia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (195, '1', 'SV', 'Salvador', 'El Salvador');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (196, '1', 'WS', 'Samoa', 'Samoa');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (197, '1', 'AS', 'Samoa américaines', 'American Samoa');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (198, '1', 'ST', 'Sao Tomé-et-Principe', 'Sao Tome and Principe');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (199, '1', 'SC', 'Seychelles', 'Seychelles');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (200, '1', 'SL', 'Sierra Leone', 'Sierra Leone');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (201, '1', 'SG', 'Singapour', 'Singapore');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (202, '1', 'SI', 'Slovénie', 'Slovenia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (203, '1', 'SK', 'Slovaquie', 'Slovakia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (204, '1', 'SO', 'Somalie', 'Somalia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (205, '1', 'SD', 'Soudan', 'Sudan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (206, '1', 'LK', 'Sri Lanka', 'Sri Lanka (ex-Ceilan)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (207, '1', 'SE', 'Suède', 'Sweden');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (208, '1', 'CH', 'Suisse', 'Switzerland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (209, '1', 'SR', 'Suriname', 'Suriname');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (210, '1', 'SZ', 'Swaziland', 'Swaziland');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (211, '1', 'SY', 'Syrie', 'Syrian Arab Republic');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (212, '1', 'TW', 'Taïwan', 'Taiwan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (213, '1', 'TJ', 'Tadjikistan', 'Tajikistan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (214, '1', 'TZ', 'Tanzanie', 'Tanzania, United Republic of');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (215, '1', 'TD', 'Tchad', 'Chad');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (216, '1', 'TF', 'Terres australes françaises', 'French Southern Territories - TF');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (217, '1', 'IO', 'Territoire britannique de l''Océan Indien', 'British Indian Ocean Territory');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (218, '1', 'TH', 'Thaïlande', 'Thailand');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (219, '1', 'TL', 'Timor Oriental', 'Timor-Leste (East Timor)');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (220, '1', 'TG', 'Togo', 'Togo');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (221, '1', 'TK', 'Tokélaou', 'Tokelau');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (222, '1', 'TO', 'Tonga', 'Tonga');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (223, '1', 'TT', 'Trinité-et-Tobago', 'Trinidad & Tobago');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (224, '1', 'TN', 'Tunisie', 'Tunisia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (225, '1', 'TM', 'Turkménistan', 'Turkmenistan');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (226, '1', 'TR', 'Turquie', 'Turkey');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (227, '1', 'TV', 'Tuvalu', 'Tuvalu');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (228, '1', 'UA', 'Ukraine', 'Ukraine');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (229, '1', 'UY', 'Uruguay', 'Uruguay');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (230, '1', 'VU', 'Vanuatu', 'Vanuatu');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (231, '1', 'VE', 'Venezuela', 'Venezuela');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (232, '1', 'VN', 'Viêt Nam', 'Viet Nam');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (233, '1', 'WF', 'Wallis-et-Futuna', 'Wallis and Futuna');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (234, '1', 'YE', 'Yémen', 'Yemen');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (235, '1', 'YU', 'Yougoslavie', 'Saint Pierre and Miquelon');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (236, '1', 'ZM', 'Zambie', 'Zambia');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (237, '1', 'ZW', 'Zimbabwe', 'Zimbabwe');
INSERT INTO pays (id, actif, code, nom, nom_en) VALUES (238, '1', 'MK', 'ex-République yougoslave de Macédoine', 'Macedonia, TFYR');
