<?php

$catalogue_data = array(
    'canton' => array(
        array(
            'id' => 1,
            'actif' => '1',
            'code' => 'AG',
            'nom' => 'Argovie',
        ),
        array(
            'id' => 2,
            'actif' => '1',
            'code' => 'AR',
            'nom' => 'Appenzell Rhodes extérieures',
        ),
        array(
            'id' => 3,
            'actif' => '1',
            'code' => 'AI',
            'nom' => 'Appenzell Rhodes intérieures',
        ),
        array(
            'id' => 4,
            'actif' => '1',
            'code' => 'BL',
            'nom' => 'Bâle Campagne',
        ),
        array(
            'id' => 5,
            'actif' => '1',
            'code' => 'BS',
            'nom' => 'Bâle Ville',
        ),
        array(
            'id' => 6,
            'actif' => '1',
            'code' => 'BE',
            'nom' => 'Berne',
        ),
        array(
            'id' => 7,
            'actif' => '1',
            'code' => 'FR',
            'nom' => 'Fribourg',
        ),
        array(
            'id' => 8,
            'actif' => '1',
            'code' => 'GE',
            'nom' => 'Genève',
        ),
        array(
            'id' => 9,
            'actif' => '1',
            'code' => 'GL',
            'nom' => 'Glaris',
        ),
        array(
            'id' => 10,
            'actif' => '1',
            'code' => 'GR',
            'nom' => 'Grisons',
        ),
        array(
            'id' => 11,
            'actif' => '1',
            'code' => 'JU',
            'nom' => 'Jura',
        ),
        array(
            'id' => 12,
            'actif' => '1',
            'code' => 'LU',
            'nom' => 'Lucerne',
        ),
        array(
            'id' => 13,
            'actif' => '1',
            'code' => 'NE',
            'nom' => 'Neuchâtel',
        ),
        array(
            'id' => 14,
            'actif' => '1',
            'code' => 'NW',
            'nom' => 'Nidwald',
        ),
        array(
            'id' => 15,
            'actif' => '1',
            'code' => 'OW',
            'nom' => 'Obwald',
        ),
        array(
            'id' => 16,
            'actif' => '1',
            'code' => 'SG',
            'nom' => 'Saint Gall',
        ),
        array(
            'id' => 17,
            'actif' => '1',
            'code' => 'SH',
            'nom' => 'Schaffhouse',
        ),
        array(
            'id' => 18,
            'actif' => '1',
            'code' => 'SZ',
            'nom' => 'Schwyz',
        ),
        array(
            'id' => 19,
            'actif' => '1',
            'code' => 'SO',
            'nom' => 'Soleure',
        ),
        array(
            'id' => 20,
            'actif' => '1',
            'code' => 'TG',
            'nom' => 'Thurgovie',
        ),
        array(
            'id' => 21,
            'actif' => '1',
            'code' => 'TI',
            'nom' => 'Tessin',
        ),
        array(
            'id' => 22,
            'actif' => '1',
            'code' => 'UR',
            'nom' => 'Uri',
        ),
        array(
            'id' => 23,
            'actif' => '1',
            'code' => 'VD',
            'nom' => 'Vaud',
        ),
        array(
            'id' => 24,
            'actif' => '1',
            'code' => 'VS',
            'nom' => 'Valais',
        ),
        array(
            'id' => 25,
            'actif' => '1',
            'code' => 'ZG',
            'nom' => 'Zoug',
        ),
        array(
            'id' => 26,
            'actif' => '1',
            'code' => 'ZH',
            'nom' => 'Zurich',
        ),
    ),
    'pays' => array(
        array(
            'id' => 1,
            'actif' => '1',
            'code' => 'AF',
            'nom' => 'Afghanistan',
            'nom_en' => 'Afghanistan',
        ),
        array(
            'id' => 2,
            'actif' => '1',
            'code' => 'ZA',
            'nom' => 'Afrique du Sud',
            'nom_en' => 'South Africa',
        ),
        array(
            'id' => 3,
            'actif' => '1',
            'code' => 'AL',
            'nom' => 'Albanie',
            'nom_en' => 'Albania',
        ),
        array(
            'id' => 4,
            'actif' => '1',
            'code' => 'DZ',
            'nom' => 'Algérie',
            'nom_en' => 'Algeria',
        ),
        array(
            'id' => 5,
            'actif' => '1',
            'code' => 'DE',
            'nom' => 'Allemagne',
            'nom_en' => 'Germany',
        ),
        array(
            'id' => 6,
            'actif' => '1',
            'code' => 'AD',
            'nom' => 'Andorre',
            'nom_en' => 'Andorra',
        ),
        array(
            'id' => 7,
            'actif' => '1',
            'code' => 'AO',
            'nom' => 'Angola',
            'nom_en' => 'Angola',
        ),
        array(
            'id' => 8,
            'actif' => '1',
            'code' => 'AI',
            'nom' => 'Anguilla',
            'nom_en' => 'Anguilla',
        ),
        array(
            'id' => 9,
            'actif' => '1',
            'code' => 'AQ',
            'nom' => 'Antarctique',
            'nom_en' => 'Antarctica',
        ),
        array(
            'id' => 10,
            'actif' => '1',
            'code' => 'AG',
            'nom' => 'Antigua-et-Barbuda',
            'nom_en' => 'Antigua & Barbuda',
        ),
        array(
            'id' => 11,
            'actif' => '1',
            'code' => 'AN',
            'nom' => 'Antilles néerlandaises',
            'nom_en' => 'Netherlands Antilles',
        ),
        array(
            'id' => 12,
            'actif' => '1',
            'code' => 'SA',
            'nom' => 'Arabie saoudite',
            'nom_en' => 'Saudi Arabia',
        ),
        array(
            'id' => 13,
            'actif' => '1',
            'code' => 'AR',
            'nom' => 'Argentine',
            'nom_en' => 'Argentina',
        ),
        array(
            'id' => 14,
            'actif' => '1',
            'code' => 'AM',
            'nom' => 'Arménie',
            'nom_en' => 'Armenia',
        ),
        array(
            'id' => 15,
            'actif' => '1',
            'code' => 'AW',
            'nom' => 'Aruba',
            'nom_en' => 'Aruba',
        ),
        array(
            'id' => 16,
            'actif' => '1',
            'code' => 'AU',
            'nom' => 'Australie',
            'nom_en' => 'Australia',
        ),
        array(
            'id' => 17,
            'actif' => '1',
            'code' => 'AT',
            'nom' => 'Autriche',
            'nom_en' => 'Austria',
        ),
        array(
            'id' => 18,
            'actif' => '1',
            'code' => 'AZ',
            'nom' => 'Azerbaïdjan',
            'nom_en' => 'Azerbaijan',
        ),
        array(
            'id' => 19,
            'actif' => '1',
            'code' => 'BJ',
            'nom' => 'Bénin',
            'nom_en' => 'Benin',
        ),
        array(
            'id' => 20,
            'actif' => '1',
            'code' => 'BS',
            'nom' => 'Bahamas',
            'nom_en' => 'Bahamas, The',
        ),
        array(
            'id' => 21,
            'actif' => '1',
            'code' => 'BH',
            'nom' => 'Bahreïn',
            'nom_en' => 'Bahrain',
        ),
        array(
            'id' => 22,
            'actif' => '1',
            'code' => 'BD',
            'nom' => 'Bangladesh',
            'nom_en' => 'Bangladesh',
        ),
        array(
            'id' => 23,
            'actif' => '1',
            'code' => 'BB',
            'nom' => 'Barbade',
            'nom_en' => 'Barbados',
        ),
        array(
            'id' => 24,
            'actif' => '1',
            'code' => 'PW',
            'nom' => 'Belau',
            'nom_en' => 'Palau',
        ),
        array(
            'id' => 25,
            'actif' => '1',
            'code' => 'BE',
            'nom' => 'Belgique',
            'nom_en' => 'Belgium',
        ),
        array(
            'id' => 26,
            'actif' => '1',
            'code' => 'BZ',
            'nom' => 'Belize',
            'nom_en' => 'Belize',
        ),
        array(
            'id' => 27,
            'actif' => '1',
            'code' => 'BM',
            'nom' => 'Bermudes',
            'nom_en' => 'Bermuda',
        ),
        array(
            'id' => 28,
            'actif' => '1',
            'code' => 'BT',
            'nom' => 'Bhoutan',
            'nom_en' => 'Bhutan',
        ),
        array(
            'id' => 29,
            'actif' => '1',
            'code' => 'BY',
            'nom' => 'Biélorussie',
            'nom_en' => 'Belarus',
        ),
        array(
            'id' => 30,
            'actif' => '1',
            'code' => 'MM',
            'nom' => 'Birmanie',
            'nom_en' => 'Myanmar (ex-Burma)',
        ),
        array(
            'id' => 31,
            'actif' => '1',
            'code' => 'BO',
            'nom' => 'Bolivie',
            'nom_en' => 'Bolivia',
        ),
        array(
            'id' => 32,
            'actif' => '1',
            'code' => 'BA',
            'nom' => 'Bosnie-Herzégovine',
            'nom_en' => 'Bosnia and Herzegovina',
        ),
        array(
            'id' => 33,
            'actif' => '1',
            'code' => 'BW',
            'nom' => 'Botswana',
            'nom_en' => 'Botswana',
        ),
        array(
            'id' => 34,
            'actif' => '1',
            'code' => 'BR',
            'nom' => 'Brésil',
            'nom_en' => 'Brazil',
        ),
        array(
            'id' => 35,
            'actif' => '1',
            'code' => 'BN',
            'nom' => 'Brunei',
            'nom_en' => 'Brunei Darussalam',
        ),
        array(
            'id' => 36,
            'actif' => '1',
            'code' => 'BG',
            'nom' => 'Bulgarie',
            'nom_en' => 'Bulgaria',
        ),
        array(
            'id' => 37,
            'actif' => '1',
            'code' => 'BF',
            'nom' => 'Burkina Faso',
            'nom_en' => 'Burkina Faso',
        ),
        array(
            'id' => 38,
            'actif' => '1',
            'code' => 'BI',
            'nom' => 'Burundi',
            'nom_en' => 'Burundi',
        ),
        array(
            'id' => 39,
            'actif' => '1',
            'code' => 'CI',
            'nom' => 'Côte d\'Ivoire',
            'nom_en' => 'Ivory Coast (see Cote d\'Ivoire)',
        ),
        array(
            'id' => 40,
            'actif' => '1',
            'code' => 'KH',
            'nom' => 'Cambodge',
            'nom_en' => 'Cambodia',
        ),
        array(
            'id' => 41,
            'actif' => '1',
            'code' => 'CM',
            'nom' => 'Cameroun',
            'nom_en' => 'Cameroon',
        ),
        array(
            'id' => 42,
            'actif' => '1',
            'code' => 'CA',
            'nom' => 'Canada',
            'nom_en' => 'Canada',
        ),
        array(
            'id' => 43,
            'actif' => '1',
            'code' => 'CV',
            'nom' => 'Cap-Vert',
            'nom_en' => 'Cape Verde',
        ),
        array(
            'id' => 44,
            'actif' => '1',
            'code' => 'CL',
            'nom' => 'Chili',
            'nom_en' => 'Chile',
        ),
        array(
            'id' => 45,
            'actif' => '1',
            'code' => 'CN',
            'nom' => 'Chine',
            'nom_en' => 'China',
        ),
        array(
            'id' => 46,
            'actif' => '1',
            'code' => 'CY',
            'nom' => 'Chypre',
            'nom_en' => 'Cyprus',
        ),
        array(
            'id' => 47,
            'actif' => '1',
            'code' => 'CO',
            'nom' => 'Colombie',
            'nom_en' => 'Colombia',
        ),
        array(
            'id' => 48,
            'actif' => '1',
            'code' => 'KM',
            'nom' => 'Comores',
            'nom_en' => 'Comoros',
        ),
        array(
            'id' => 49,
            'actif' => '1',
            'code' => 'CG',
            'nom' => 'Congo',
            'nom_en' => 'Congo',
        ),
        array(
            'id' => 50,
            'actif' => '1',
            'code' => 'KP',
            'nom' => 'Corée du Nord',
            'nom_en' => 'Korea, Demo. People\'s Rep. of',
        ),
        array(
            'id' => 51,
            'actif' => '1',
            'code' => 'KR',
            'nom' => 'Corée du Sud',
            'nom_en' => 'Korea, (South) Republic of',
        ),
        array(
            'id' => 52,
            'actif' => '1',
            'code' => 'CR',
            'nom' => 'Costa Rica',
            'nom_en' => 'Costa Rica',
        ),
        array(
            'id' => 53,
            'actif' => '1',
            'code' => 'HR',
            'nom' => 'Croatie',
            'nom_en' => 'Croatia',
        ),
        array(
            'id' => 54,
            'actif' => '1',
            'code' => 'CU',
            'nom' => 'Cuba',
            'nom_en' => 'Cuba',
        ),
        array(
            'id' => 55,
            'actif' => '1',
            'code' => 'DK',
            'nom' => 'Danemark',
            'nom_en' => 'Denmark',
        ),
        array(
            'id' => 56,
            'actif' => '1',
            'code' => 'DJ',
            'nom' => 'Djibouti',
            'nom_en' => 'Djibouti',
        ),
        array(
            'id' => 57,
            'actif' => '1',
            'code' => 'DM',
            'nom' => 'Dominique',
            'nom_en' => 'Dominica',
        ),
        array(
            'id' => 58,
            'actif' => '1',
            'code' => 'EG',
            'nom' => 'Égypte',
            'nom_en' => 'Egypt',
        ),
        array(
            'id' => 59,
            'actif' => '1',
            'code' => 'AE',
            'nom' => 'Émirats arabes unis',
            'nom_en' => 'United Arab Emirates',
        ),
        array(
            'id' => 60,
            'actif' => '1',
            'code' => 'EC',
            'nom' => 'Équateur',
            'nom_en' => 'Ecuador',
        ),
        array(
            'id' => 61,
            'actif' => '1',
            'code' => 'ER',
            'nom' => 'Érythrée',
            'nom_en' => 'Eritrea',
        ),
        array(
            'id' => 62,
            'actif' => '1',
            'code' => 'ES',
            'nom' => 'Espagne',
            'nom_en' => 'Spain',
        ),
        array(
            'id' => 63,
            'actif' => '1',
            'code' => 'EE',
            'nom' => 'Estonie',
            'nom_en' => 'Estonia',
        ),
        array(
            'id' => 64,
            'actif' => '1',
            'code' => 'US',
            'nom' => 'États-Unis',
            'nom_en' => 'United States',
        ),
        array(
            'id' => 65,
            'actif' => '1',
            'code' => 'ET',
            'nom' => 'Éthiopie',
            'nom_en' => 'Ethiopia',
        ),
        array(
            'id' => 66,
            'actif' => '1',
            'code' => 'FI',
            'nom' => 'Finlande',
            'nom_en' => 'Finland',
        ),
        array(
            'id' => 67,
            'actif' => '1',
            'code' => 'FR',
            'nom' => 'France',
            'nom_en' => 'France',
        ),
        array(
            'id' => 68,
            'actif' => '1',
            'code' => 'GE',
            'nom' => 'Géorgie',
            'nom_en' => 'Georgia',
        ),
        array(
            'id' => 69,
            'actif' => '1',
            'code' => 'GA',
            'nom' => 'Gabon',
            'nom_en' => 'Gabon',
        ),
        array(
            'id' => 70,
            'actif' => '1',
            'code' => 'GM',
            'nom' => 'Gambie',
            'nom_en' => 'Gambia, the',
        ),
        array(
            'id' => 71,
            'actif' => '1',
            'code' => 'GH',
            'nom' => 'Ghana',
            'nom_en' => 'Ghana',
        ),
        array(
            'id' => 72,
            'actif' => '1',
            'code' => 'GI',
            'nom' => 'Gibraltar',
            'nom_en' => 'Gibraltar',
        ),
        array(
            'id' => 73,
            'actif' => '1',
            'code' => 'GR',
            'nom' => 'Grèce',
            'nom_en' => 'Greece',
        ),
        array(
            'id' => 74,
            'actif' => '1',
            'code' => 'GD',
            'nom' => 'Grenade',
            'nom_en' => 'Grenada',
        ),
        array(
            'id' => 75,
            'actif' => '1',
            'code' => 'GL',
            'nom' => 'Groenland',
            'nom_en' => 'Greenland',
        ),
        array(
            'id' => 76,
            'actif' => '1',
            'code' => 'GP',
            'nom' => 'Guadeloupe',
            'nom_en' => 'Guinea, Equatorial',
        ),
        array(
            'id' => 77,
            'actif' => '1',
            'code' => 'GU',
            'nom' => 'Guam',
            'nom_en' => 'Guam',
        ),
        array(
            'id' => 78,
            'actif' => '1',
            'code' => 'GT',
            'nom' => 'Guatemala',
            'nom_en' => 'Guatemala',
        ),
        array(
            'id' => 79,
            'actif' => '1',
            'code' => 'GN',
            'nom' => 'Guinée',
            'nom_en' => 'Guinea',
        ),
        array(
            'id' => 80,
            'actif' => '1',
            'code' => 'GQ',
            'nom' => 'Guinée équatoriale',
            'nom_en' => 'Equatorial Guinea',
        ),
        array(
            'id' => 81,
            'actif' => '1',
            'code' => 'GW',
            'nom' => 'Guinée-Bissao',
            'nom_en' => 'Guinea-Bissau',
        ),
        array(
            'id' => 82,
            'actif' => '1',
            'code' => 'GY',
            'nom' => 'Guyana',
            'nom_en' => 'Guyana',
        ),
        array(
            'id' => 83,
            'actif' => '1',
            'code' => 'GF',
            'nom' => 'Guyane française',
            'nom_en' => 'Guiana, French',
        ),
        array(
            'id' => 84,
            'actif' => '1',
            'code' => 'HT',
            'nom' => 'Haïti',
            'nom_en' => 'Haiti',
        ),
        array(
            'id' => 85,
            'actif' => '1',
            'code' => 'HN',
            'nom' => 'Honduras',
            'nom_en' => 'Honduras',
        ),
        array(
            'id' => 86,
            'actif' => '1',
            'code' => 'HK',
            'nom' => 'Hong Kong',
            'nom_en' => 'Hong Kong, (China)',
        ),
        array(
            'id' => 87,
            'actif' => '1',
            'code' => 'HU',
            'nom' => 'Hongrie',
            'nom_en' => 'Hungary',
        ),
        array(
            'id' => 88,
            'actif' => '1',
            'code' => 'BV',
            'nom' => 'Ile Bouvet',
            'nom_en' => 'Bouvet Island',
        ),
        array(
            'id' => 89,
            'actif' => '1',
            'code' => 'CX',
            'nom' => 'Ile Christmas',
            'nom_en' => 'Christmas Island',
        ),
        array(
            'id' => 90,
            'actif' => '1',
            'code' => 'NF',
            'nom' => 'Ile Norfolk',
            'nom_en' => 'Norfolk Island',
        ),
        array(
            'id' => 91,
            'actif' => '1',
            'code' => 'KY',
            'nom' => 'Iles Cayman',
            'nom_en' => 'Cayman Islands',
        ),
        array(
            'id' => 92,
            'actif' => '1',
            'code' => 'CK',
            'nom' => 'Iles Cook',
            'nom_en' => 'Cook Islands',
        ),
        array(
            'id' => 93,
            'actif' => '1',
            'code' => 'FO',
            'nom' => 'Iles Féroé',
            'nom_en' => 'Faroe Islands',
        ),
        array(
            'id' => 94,
            'actif' => '1',
            'code' => 'FK',
            'nom' => 'Iles Falkland',
            'nom_en' => 'Falkland Islands (Malvinas)',
        ),
        array(
            'id' => 95,
            'actif' => '1',
            'code' => 'FJ',
            'nom' => 'Iles Fidji',
            'nom_en' => 'Fiji',
        ),
        array(
            'id' => 96,
            'actif' => '1',
            'code' => 'GS',
            'nom' => 'Iles Géorgie du Sud et Sandwich du Sud',
            'nom_en' => 'S. Georgia and S. Sandwich Is.',
        ),
        array(
            'id' => 97,
            'actif' => '1',
            'code' => 'HM',
            'nom' => 'Iles Heard et McDonald',
            'nom_en' => 'Heard and McDonald Islands',
        ),
        array(
            'id' => 98,
            'actif' => '1',
            'code' => 'MH',
            'nom' => 'Iles Marshall',
            'nom_en' => 'Marshall Islands',
        ),
        array(
            'id' => 99,
            'actif' => '1',
            'code' => 'PN',
            'nom' => 'Iles Pitcairn',
            'nom_en' => 'Pitcairn Island',
        ),
        array(
            'id' => 100,
            'actif' => '1',
            'code' => 'SB',
            'nom' => 'Iles Salomon',
            'nom_en' => 'Solomon Islands',
        ),
        array(
            'id' => 101,
            'actif' => '1',
            'code' => 'SJ',
            'nom' => 'Iles Svalbard et Jan Mayen',
            'nom_en' => 'Svalbard and Jan Mayen Islands',
        ),
        array(
            'id' => 102,
            'actif' => '1',
            'code' => 'TC',
            'nom' => 'Iles Turks-et-Caicos',
            'nom_en' => 'Turks and Caicos Islands',
        ),
        array(
            'id' => 103,
            'actif' => '1',
            'code' => 'VI',
            'nom' => 'Iles Vierges américaines',
            'nom_en' => 'Virgin Islands, U.S.',
        ),
        array(
            'id' => 104,
            'actif' => '1',
            'code' => 'VG',
            'nom' => 'Iles Vierges britanniques',
            'nom_en' => 'Virgin Islands, British',
        ),
        array(
            'id' => 105,
            'actif' => '1',
            'code' => 'CC',
            'nom' => 'Iles des Cocos (Keeling)',
            'nom_en' => 'Cocos (Keeling) Islands',
        ),
        array(
            'id' => 106,
            'actif' => '1',
            'code' => 'UM',
            'nom' => 'Iles mineures éloignées des États-Unis',
            'nom_en' => 'US Minor Outlying Islands',
        ),
        array(
            'id' => 107,
            'actif' => '1',
            'code' => 'IN',
            'nom' => 'Inde',
            'nom_en' => 'India',
        ),
        array(
            'id' => 108,
            'actif' => '1',
            'code' => 'ID',
            'nom' => 'Indonésie',
            'nom_en' => 'Indonesia',
        ),
        array(
            'id' => 109,
            'actif' => '1',
            'code' => 'IR',
            'nom' => 'Iran',
            'nom_en' => 'Iran, Islamic Republic of',
        ),
        array(
            'id' => 110,
            'actif' => '1',
            'code' => 'IQ',
            'nom' => 'Iraq',
            'nom_en' => 'Iraq',
        ),
        array(
            'id' => 111,
            'actif' => '1',
            'code' => 'IE',
            'nom' => 'Irlande',
            'nom_en' => 'Ireland',
        ),
        array(
            'id' => 112,
            'actif' => '1',
            'code' => 'IS',
            'nom' => 'Islande',
            'nom_en' => 'Iceland',
        ),
        array(
            'id' => 113,
            'actif' => '1',
            'code' => 'IL',
            'nom' => 'IsraÃ«l',
            'nom_en' => 'Israel',
        ),
        array(
            'id' => 114,
            'actif' => '1',
            'code' => 'IT',
            'nom' => 'Italie',
            'nom_en' => 'Italy',
        ),
        array(
            'id' => 115,
            'actif' => '1',
            'code' => 'JM',
            'nom' => 'Jamaïque',
            'nom_en' => 'Jamaica',
        ),
        array(
            'id' => 116,
            'actif' => '1',
            'code' => 'JP',
            'nom' => 'Japon',
            'nom_en' => 'Japan',
        ),
        array(
            'id' => 117,
            'actif' => '1',
            'code' => 'JO',
            'nom' => 'Jordanie',
            'nom_en' => 'Jordan',
        ),
        array(
            'id' => 118,
            'actif' => '1',
            'code' => 'KZ',
            'nom' => 'Kazakhstan',
            'nom_en' => 'Kazakhstan',
        ),
        array(
            'id' => 119,
            'actif' => '1',
            'code' => 'KE',
            'nom' => 'Kenya',
            'nom_en' => 'Kenya',
        ),
        array(
            'id' => 120,
            'actif' => '1',
            'code' => 'KG',
            'nom' => 'Kirghizistan',
            'nom_en' => 'Kyrgyzstan',
        ),
        array(
            'id' => 121,
            'actif' => '1',
            'code' => 'KI',
            'nom' => 'Kiribati',
            'nom_en' => 'Kiribati',
        ),
        array(
            'id' => 122,
            'actif' => '1',
            'code' => 'KW',
            'nom' => 'Koweït',
            'nom_en' => 'Kuwait',
        ),
        array(
            'id' => 123,
            'actif' => '1',
            'code' => 'LA',
            'nom' => 'Laos',
            'nom_en' => 'Lao People\'s Democratic Republic',
        ),
        array(
            'id' => 124,
            'actif' => '1',
            'code' => 'LS',
            'nom' => 'Lesotho',
            'nom_en' => 'Lesotho',
        ),
        array(
            'id' => 125,
            'actif' => '1',
            'code' => 'LV',
            'nom' => 'Lettonie',
            'nom_en' => 'Latvia',
        ),
        array(
            'id' => 126,
            'actif' => '1',
            'code' => 'LB',
            'nom' => 'Liban',
            'nom_en' => 'Lebanon',
        ),
        array(
            'id' => 127,
            'actif' => '1',
            'code' => 'LR',
            'nom' => 'Liberia',
            'nom_en' => 'Liberia',
        ),
        array(
            'id' => 128,
            'actif' => '1',
            'code' => 'LY',
            'nom' => 'Libye',
            'nom_en' => 'Libyan Arab Jamahiriya',
        ),
        array(
            'id' => 129,
            'actif' => '1',
            'code' => 'LI',
            'nom' => 'Liechtenstein',
            'nom_en' => 'Liechtenstein',
        ),
        array(
            'id' => 130,
            'actif' => '1',
            'code' => 'LT',
            'nom' => 'Lituanie',
            'nom_en' => 'Lithuania',
        ),
        array(
            'id' => 131,
            'actif' => '1',
            'code' => 'LU',
            'nom' => 'Luxembourg',
            'nom_en' => 'Luxembourg',
        ),
        array(
            'id' => 132,
            'actif' => '1',
            'code' => 'MO',
            'nom' => 'Macao',
            'nom_en' => 'Macao, (China)',
        ),
        array(
            'id' => 133,
            'actif' => '1',
            'code' => 'MG',
            'nom' => 'Madagascar',
            'nom_en' => 'Madagascar',
        ),
        array(
            'id' => 134,
            'actif' => '1',
            'code' => 'MY',
            'nom' => 'Malaisie',
            'nom_en' => 'Malaysia',
        ),
        array(
            'id' => 135,
            'actif' => '1',
            'code' => 'MW',
            'nom' => 'Malawi',
            'nom_en' => 'Malawi',
        ),
        array(
            'id' => 136,
            'actif' => '1',
            'code' => 'MV',
            'nom' => 'Maldives',
            'nom_en' => 'Maldives',
        ),
        array(
            'id' => 137,
            'actif' => '1',
            'code' => 'ML',
            'nom' => 'Mali',
            'nom_en' => 'Mali',
        ),
        array(
            'id' => 138,
            'actif' => '1',
            'code' => 'MT',
            'nom' => 'Malte',
            'nom_en' => 'Malta',
        ),
        array(
            'id' => 139,
            'actif' => '1',
            'code' => 'MP',
            'nom' => 'Mariannes du Nord',
            'nom_en' => 'Northern Mariana Islands',
        ),
        array(
            'id' => 140,
            'actif' => '1',
            'code' => 'MA',
            'nom' => 'Maroc',
            'nom_en' => 'Morocco',
        ),
        array(
            'id' => 141,
            'actif' => '1',
            'code' => 'MQ',
            'nom' => 'Martinique',
            'nom_en' => 'Martinique',
        ),
        array(
            'id' => 142,
            'actif' => '1',
            'code' => 'MU',
            'nom' => 'Maurice',
            'nom_en' => 'Mauritius',
        ),
        array(
            'id' => 143,
            'actif' => '1',
            'code' => 'MR',
            'nom' => 'Mauritanie',
            'nom_en' => 'Mauritania',
        ),
        array(
            'id' => 144,
            'actif' => '1',
            'code' => 'YT',
            'nom' => 'Mayotte',
            'nom_en' => 'Mayotte',
        ),
        array(
            'id' => 145,
            'actif' => '1',
            'code' => 'MX',
            'nom' => 'Mexique',
            'nom_en' => 'Mexico',
        ),
        array(
            'id' => 146,
            'actif' => '1',
            'code' => 'FM',
            'nom' => 'Micronésie',
            'nom_en' => 'Micronesia, Federated States of',
        ),
        array(
            'id' => 147,
            'actif' => '1',
            'code' => 'MD',
            'nom' => 'Moldavie',
            'nom_en' => 'Moldova, Republic of',
        ),
        array(
            'id' => 148,
            'actif' => '1',
            'code' => 'MC',
            'nom' => 'Monaco',
            'nom_en' => 'Monaco',
        ),
        array(
            'id' => 149,
            'actif' => '1',
            'code' => 'MN',
            'nom' => 'Mongolie',
            'nom_en' => 'Mongolia',
        ),
        array(
            'id' => 150,
            'actif' => '1',
            'code' => 'MS',
            'nom' => 'Montserrat',
            'nom_en' => 'Montserrat',
        ),
        array(
            'id' => 151,
            'actif' => '1',
            'code' => 'MZ',
            'nom' => 'Mozambique',
            'nom_en' => 'Mozambique',
        ),
        array(
            'id' => 152,
            'actif' => '1',
            'code' => 'NP',
            'nom' => 'Népal',
            'nom_en' => 'Nepal',
        ),
        array(
            'id' => 153,
            'actif' => '1',
            'code' => 'NA',
            'nom' => 'Namibie',
            'nom_en' => 'Namibia',
        ),
        array(
            'id' => 154,
            'actif' => '1',
            'code' => 'NR',
            'nom' => 'Nauru',
            'nom_en' => 'Nauru',
        ),
        array(
            'id' => 155,
            'actif' => '1',
            'code' => 'NI',
            'nom' => 'Nicaragua',
            'nom_en' => 'Nicaragua',
        ),
        array(
            'id' => 156,
            'actif' => '1',
            'code' => 'NE',
            'nom' => 'Niger',
            'nom_en' => 'Niger',
        ),
        array(
            'id' => 157,
            'actif' => '1',
            'code' => 'NG',
            'nom' => 'Nigeria',
            'nom_en' => 'Nigeria',
        ),
        array(
            'id' => 158,
            'actif' => '1',
            'code' => 'NU',
            'nom' => 'Nioué',
            'nom_en' => 'Niue',
        ),
        array(
            'id' => 159,
            'actif' => '1',
            'code' => 'NO',
            'nom' => 'Norvège',
            'nom_en' => 'Norway',
        ),
        array(
            'id' => 160,
            'actif' => '1',
            'code' => 'NC',
            'nom' => 'Nouvelle-Calédonie',
            'nom_en' => 'New Caledonia',
        ),
        array(
            'id' => 161,
            'actif' => '1',
            'code' => 'NZ',
            'nom' => 'Nouvelle-Zélande',
            'nom_en' => 'New Zealand',
        ),
        array(
            'id' => 162,
            'actif' => '1',
            'code' => 'OM',
            'nom' => 'Oman',
            'nom_en' => 'Oman',
        ),
        array(
            'id' => 163,
            'actif' => '1',
            'code' => 'UG',
            'nom' => 'Ouganda',
            'nom_en' => 'Uganda',
        ),
        array(
            'id' => 164,
            'actif' => '1',
            'code' => 'UZ',
            'nom' => 'Ouzbékistan',
            'nom_en' => 'Uzbekistan',
        ),
        array(
            'id' => 165,
            'actif' => '1',
            'code' => 'PE',
            'nom' => 'Pérou',
            'nom_en' => 'Peru',
        ),
        array(
            'id' => 166,
            'actif' => '1',
            'code' => 'PK',
            'nom' => 'Pakistan',
            'nom_en' => 'Pakistan',
        ),
        array(
            'id' => 167,
            'actif' => '1',
            'code' => 'PA',
            'nom' => 'Panama',
            'nom_en' => 'Panama',
        ),
        array(
            'id' => 168,
            'actif' => '1',
            'code' => 'PG',
            'nom' => 'Papouasie-Nouvelle-Guinée',
            'nom_en' => 'Papua New Guinea',
        ),
        array(
            'id' => 169,
            'actif' => '1',
            'code' => 'PY',
            'nom' => 'Paraguay',
            'nom_en' => 'Paraguay',
        ),
        array(
            'id' => 170,
            'actif' => '1',
            'code' => 'NL',
            'nom' => 'Pays-Bas',
            'nom_en' => 'Netherlands',
        ),
        array(
            'id' => 171,
            'actif' => '1',
            'code' => 'PH',
            'nom' => 'Philippines',
            'nom_en' => 'Philippines',
        ),
        array(
            'id' => 172,
            'actif' => '1',
            'code' => 'PL',
            'nom' => 'Pologne',
            'nom_en' => 'Poland',
        ),
        array(
            'id' => 173,
            'actif' => '1',
            'code' => 'PF',
            'nom' => 'Polynésie française',
            'nom_en' => 'French Polynesia',
        ),
        array(
            'id' => 174,
            'actif' => '1',
            'code' => 'PR',
            'nom' => 'Porto Rico',
            'nom_en' => 'Puerto Rico',
        ),
        array(
            'id' => 175,
            'actif' => '1',
            'code' => 'PT',
            'nom' => 'Portugal',
            'nom_en' => 'Portugal',
        ),
        array(
            'id' => 176,
            'actif' => '1',
            'code' => 'QA',
            'nom' => 'Qatar',
            'nom_en' => 'Qatar',
        ),
        array(
            'id' => 177,
            'actif' => '1',
            'code' => 'CF',
            'nom' => 'République centrafricaine',
            'nom_en' => 'Central African Republic',
        ),
        array(
            'id' => 178,
            'actif' => '1',
            'code' => 'CD',
            'nom' => 'République démocratique du Congo',
            'nom_en' => 'Congo, Democratic Rep. of the',
        ),
        array(
            'id' => 179,
            'actif' => '1',
            'code' => 'DO',
            'nom' => 'République dominicaine',
            'nom_en' => 'Dominican Republic',
        ),
        array(
            'id' => 180,
            'actif' => '1',
            'code' => 'CZ',
            'nom' => 'République tchèque',
            'nom_en' => 'Czech Republic',
        ),
        array(
            'id' => 181,
            'actif' => '1',
            'code' => 'RE',
            'nom' => 'Réunion',
            'nom_en' => 'Reunion',
        ),
        array(
            'id' => 182,
            'actif' => '1',
            'code' => 'RO',
            'nom' => 'Roumanie',
            'nom_en' => 'Romania',
        ),
        array(
            'id' => 183,
            'actif' => '1',
            'code' => 'GB',
            'nom' => 'Royaume-Uni',
            'nom_en' => 'Saint Pierre and Miquelon',
        ),
        array(
            'id' => 184,
            'actif' => '1',
            'code' => 'RU',
            'nom' => 'Russie',
            'nom_en' => 'Russia (Russian Federation)',
        ),
        array(
            'id' => 185,
            'actif' => '1',
            'code' => 'RW',
            'nom' => 'Rwanda',
            'nom_en' => 'Rwanda',
        ),
        array(
            'id' => 186,
            'actif' => '1',
            'code' => 'SN',
            'nom' => 'Sénégal',
            'nom_en' => 'Senegal',
        ),
        array(
            'id' => 187,
            'actif' => '1',
            'code' => 'EH',
            'nom' => 'Sahara occidental',
            'nom_en' => 'Western Sahara',
        ),
        array(
            'id' => 188,
            'actif' => '1',
            'code' => 'KN',
            'nom' => 'Saint-Christophe-et-Niévès',
            'nom_en' => 'Saint Kitts and Nevis',
        ),
        array(
            'id' => 189,
            'actif' => '1',
            'code' => 'SM',
            'nom' => 'Saint-Marin',
            'nom_en' => 'San Marino',
        ),
        array(
            'id' => 190,
            'actif' => '1',
            'code' => 'PM',
            'nom' => 'Saint-Pierre-et-Miquelon',
            'nom_en' => 'Saint Pierre and Miquelon',
        ),
        array(
            'id' => 191,
            'actif' => '1',
            'code' => 'VA',
            'nom' => 'Saint-Siège',
            'nom_en' => 'Vatican City State (Holy See)',
        ),
        array(
            'id' => 192,
            'actif' => '1',
            'code' => 'VC',
            'nom' => 'Saint-Vincent-et-les-Grenadines',
            'nom_en' => 'Saint Vincent and the Grenadines',
        ),
        array(
            'id' => 193,
            'actif' => '1',
            'code' => 'SH',
            'nom' => 'Sainte-Hélène',
            'nom_en' => 'Saint Helena',
        ),
        array(
            'id' => 194,
            'actif' => '1',
            'code' => 'LC',
            'nom' => 'Sainte-Lucie',
            'nom_en' => 'Saint Lucia',
        ),
        array(
            'id' => 195,
            'actif' => '1',
            'code' => 'SV',
            'nom' => 'Salvador',
            'nom_en' => 'El Salvador',
        ),
        array(
            'id' => 196,
            'actif' => '1',
            'code' => 'WS',
            'nom' => 'Samoa',
            'nom_en' => 'Samoa',
        ),
        array(
            'id' => 197,
            'actif' => '1',
            'code' => 'AS',
            'nom' => 'Samoa américaines',
            'nom_en' => 'American Samoa',
        ),
        array(
            'id' => 198,
            'actif' => '1',
            'code' => 'ST',
            'nom' => 'Sao Tomé-et-Principe',
            'nom_en' => 'Sao Tome and Principe',
        ),
        array(
            'id' => 199,
            'actif' => '1',
            'code' => 'SC',
            'nom' => 'Seychelles',
            'nom_en' => 'Seychelles',
        ),
        array(
            'id' => 200,
            'actif' => '1',
            'code' => 'SL',
            'nom' => 'Sierra Leone',
            'nom_en' => 'Sierra Leone',
        ),
        array(
            'id' => 201,
            'actif' => '1',
            'code' => 'SG',
            'nom' => 'Singapour',
            'nom_en' => 'Singapore',
        ),
        array(
            'id' => 202,
            'actif' => '1',
            'code' => 'SI',
            'nom' => 'Slovénie',
            'nom_en' => 'Slovenia',
        ),
        array(
            'id' => 203,
            'actif' => '1',
            'code' => 'SK',
            'nom' => 'Slovaquie',
            'nom_en' => 'Slovakia',
        ),
        array(
            'id' => 204,
            'actif' => '1',
            'code' => 'SO',
            'nom' => 'Somalie',
            'nom_en' => 'Somalia',
        ),
        array(
            'id' => 205,
            'actif' => '1',
            'code' => 'SD',
            'nom' => 'Soudan',
            'nom_en' => 'Sudan',
        ),
        array(
            'id' => 206,
            'actif' => '1',
            'code' => 'LK',
            'nom' => 'Sri Lanka',
            'nom_en' => 'Sri Lanka (ex-Ceilan)',
        ),
        array(
            'id' => 207,
            'actif' => '1',
            'code' => 'SE',
            'nom' => 'Suède',
            'nom_en' => 'Sweden',
        ),
        array(
            'id' => 208,
            'actif' => '1',
            'code' => 'CH',
            'nom' => 'Suisse',
            'nom_en' => 'Switzerland',
        ),
        array(
            'id' => 209,
            'actif' => '1',
            'code' => 'SR',
            'nom' => 'Suriname',
            'nom_en' => 'Suriname',
        ),
        array(
            'id' => 210,
            'actif' => '1',
            'code' => 'SZ',
            'nom' => 'Swaziland',
            'nom_en' => 'Swaziland',
        ),
        array(
            'id' => 211,
            'actif' => '1',
            'code' => 'SY',
            'nom' => 'Syrie',
            'nom_en' => 'Syrian Arab Republic',
        ),
        array(
            'id' => 212,
            'actif' => '1',
            'code' => 'TW',
            'nom' => 'Taïwan',
            'nom_en' => 'Taiwan',
        ),
        array(
            'id' => 213,
            'actif' => '1',
            'code' => 'TJ',
            'nom' => 'Tadjikistan',
            'nom_en' => 'Tajikistan',
        ),
        array(
            'id' => 214,
            'actif' => '1',
            'code' => 'TZ',
            'nom' => 'Tanzanie',
            'nom_en' => 'Tanzania, United Republic of',
        ),
        array(
            'id' => 215,
            'actif' => '1',
            'code' => 'TD',
            'nom' => 'Tchad',
            'nom_en' => 'Chad',
        ),
        array(
            'id' => 216,
            'actif' => '1',
            'code' => 'TF',
            'nom' => 'Terres australes françaises',
            'nom_en' => 'French Southern Territories - TF',
        ),
        array(
            'id' => 217,
            'actif' => '1',
            'code' => 'IO',
            'nom' => 'Territoire britannique de l\'Océan Indien',
            'nom_en' => 'British Indian Ocean Territory',
        ),
        array(
            'id' => 218,
            'actif' => '1',
            'code' => 'TH',
            'nom' => 'Thaïlande',
            'nom_en' => 'Thailand',
        ),
        array(
            'id' => 219,
            'actif' => '1',
            'code' => 'KE',
            'nom' => 'Kenya',
            'nom_en' => 'Kenya',
        ),
        array(
            'id' => 220,
            'actif' => '1',
            'code' => 'TG',
            'nom' => 'Togo',
            'nom_en' => 'Togo',
        ),
        array(
            'id' => 221,
            'actif' => '1',
            'code' => 'TK',
            'nom' => 'Tokélaou',
            'nom_en' => 'Tokelau',
        ),
        array(
            'id' => 222,
            'actif' => '1',
            'code' => 'TO',
            'nom' => 'Tonga',
            'nom_en' => 'Tonga',
        ),
        array(
            'id' => 223,
            'actif' => '1',
            'code' => 'TT',
            'nom' => 'Trinité-et-Tobago',
            'nom_en' => 'Trinidad & Tobago',
        ),
        array(
            'id' => 224,
            'actif' => '1',
            'code' => 'TN',
            'nom' => 'Tunisie',
            'nom_en' => 'Tunisia',
        ),
        array(
            'id' => 225,
            'actif' => '1',
            'code' => 'TM',
            'nom' => 'Turkménistan',
            'nom_en' => 'Turkmenistan',
        ),
        array(
            'id' => 226,
            'actif' => '1',
            'code' => 'TR',
            'nom' => 'Turquie',
            'nom_en' => 'Turkey',
        ),
        array(
            'id' => 227,
            'actif' => '1',
            'code' => 'TV',
            'nom' => 'Tuvalu',
            'nom_en' => 'Tuvalu',
        ),
        array(
            'id' => 228,
            'actif' => '1',
            'code' => 'UA',
            'nom' => 'Ukraine',
            'nom_en' => 'Ukraine',
        ),
        array(
            'id' => 229,
            'actif' => '1',
            'code' => 'UY',
            'nom' => 'Uruguay',
            'nom_en' => 'Uruguay',
        ),
        array(
            'id' => 230,
            'actif' => '1',
            'code' => 'VU',
            'nom' => 'Vanuatu',
            'nom_en' => 'Vanuatu',
        ),
        array(
            'id' => 231,
            'actif' => '1',
            'code' => 'VE',
            'nom' => 'Venezuela',
            'nom_en' => 'Venezuela',
        ),
        array(
            'id' => 232,
            'actif' => '1',
            'code' => 'VN',
            'nom' => 'Viêt Nam',
            'nom_en' => 'Viet Nam',
        ),
        array(
            'id' => 233,
            'actif' => '1',
            'code' => 'WF',
            'nom' => 'Wallis-et-Futuna',
            'nom_en' => 'Wallis and Futuna',
        ),
        array(
            'id' => 234,
            'actif' => '1',
            'code' => 'YE',
            'nom' => 'Yémen',
            'nom_en' => 'Yemen',
        ),
        array(
            'id' => 235,
            'actif' => '1',
            'code' => 'YU',
            'nom' => 'Yougoslavie',
            'nom_en' => 'Saint Pierre and Miquelon',
        ),
        array(
            'id' => 236,
            'actif' => '1',
            'code' => 'ZM',
            'nom' => 'Zambie',
            'nom_en' => 'Zambia',
        ),
        array(
            'id' => 237,
            'actif' => '1',
            'code' => 'ZW',
            'nom' => 'Zimbabwe',
            'nom_en' => 'Zimbabwe',
        ),
        array(
            'id' => 238,
            'actif' => '1',
            'code' => 'MK',
            'nom' => 'ex-République yougoslave de Macédoine',
            'nom_en' => 'Macedonia, TFYR',
        ),
    ),
    'permis' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Permis A'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Permis B'
        ),
    ),
    'section' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'code' => 'SSC',
            'nom' => 'Section des sciences cliniques'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'code' => 'SSF',
            'nom' => 'Section des sciences fondamentales'
        ),
    ),
    'genre' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'genre' => 'Masculin',
            'genre_short' => 'H',
            'intitule' => 'Monsieur',
            'intitule_short' => 'M'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'genre' => 'Féminin',
            'genre_short' => 'F',
            'intitule' => 'Madame',
            'intitule_short' => 'Mme'
        ),
    ),
    'etatcivil' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Célibataire'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Marié'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Divorcé'
        ),
        array(
            'id' => '4',
            'actif' => '1',
            'nom' => 'Veuf'
        ),
    ),
    'formation' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'abreviation' => 'MD'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'abreviation' => 'PhD'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'abreviation' => 'MD-PhD'
        ),
        array(
            'id' => '4',
            'actif' => '1',
            'abreviation' => 'Autre'
        ),
        array(
            'id' => '5',
            'actif' => '1',
            'abreviation' => 'Inconnu'
        ),
    ),
    'departement' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'section_id' => '1',
            'nom' => 'SSC A'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'section_id' => '1',
            'nom' => 'SSC B'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'section_id' => '1',
            'nom' => 'SSC C'
        ),
        array(
            'id' => '4',
            'actif' => '1',
            'section_id' => '2',
            'nom' => 'SSF X'
        ),
        array(
            'id' => '5',
            'actif' => '1',
            'section_id' => '2',
            'nom' => 'SSF Y'
        ),
        array(
            'id' => '6',
            'actif' => '1',
            'section_id' => '2',
            'nom' => 'SSF Z'
        ),
    ),
    'adresse_type' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Professionnelle'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Privée'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Autre'
        ),
    ),
    'activite_type' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Fonction'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Titre académique'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Mandat'
        ),
    ),
    'activite' => array(
        array(
            'id' => 1,
            'activite_type_id' => 1,
            'section_id' => 2,
            'abreviation' => 'Autre F/SSF',
            'nom' => 'Autre fonction SSF',
        ),
        array(
            'id' => 2,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PO',
            'nom' => 'Professeur ordinaire',
        ),
        array(
            'id' => 3,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PO ad personam',
            'nom' => 'Professeur ordinaire ad personam',
        ),
        array(
            'id' => 4,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PAS',
            'nom' => 'Professeur associé',
        ),
        array(
            'id' => 5,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PAS ad personam',
            'nom' => 'Professeur associé ad personam',
        ),
        array(
            'id' => 6,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PAST',
            'nom' => 'Professeur assistant',
        ),
        array(
            'id' => 7,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PAST PTC',
            'nom' => 'Professeur assistant en prétitularisation conditionnelle',
        ),
        array(
            'id' => 8,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PAST boursier',
            'nom' => 'Professeur assistant boursier',
        ),
        array(
            'id' => 9,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PAST suppléant',
            'nom' => 'Professeur assistant suppléant',
        ),
        array(
            'id' => 10,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PTIT',
            'nom' => 'Professeur titulaire',
        ),
        array(
            'id' => 11,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PI avec indemnités',
            'nom' => 'Professeur invité avec indemnités',
        ),
        array(
            'id' => 12,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PI sans incidence financière',
            'nom' => 'Professeur invité sans incidence financière',
        ),
        array(
            'id' => 13,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PD-MER1',
            'nom' => 'Privat-docent et Maître d\'enseignement et de recherche, type 1',
        ),
        array(
            'id' => 14,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PD-MER2',
            'nom' => 'Privat-docent et Maître d\'enseignement et de recherche, type 2',
        ),
        array(
            'id' => 15,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PD',
            'nom' => 'Privat-docent',
        ),
        array(
            'id' => 16,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'PD sans incidence financière',
            'nom' => 'Privat-docent sans incidence financière',
        ),
        array(
            'id' => 17,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'MER1',
            'nom' => 'Maître d\'enseignement et de recherche, type 1',
        ),
        array(
            'id' => 18,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'MER2',
            'nom' => 'Maître d\'enseignement et de recherche, type 2',
        ),
        array(
            'id' => 19,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'CC avec indemnités',
            'nom' => 'Chargé de cours avec indemnités',
        ),
        array(
            'id' => 20,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'CC sans incidence financière',
            'nom' => 'Chargé de cours sans incidence financière',
        ),
        array(
            'id' => 21,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'MA',
            'nom' => 'Maître assistant',
        ),
        array(
            'id' => 22,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'MA suppléant',
            'nom' => 'Maître assistant suppléant',
        ),
        array(
            'id' => 23,
            'activite_type_id' => 2,
            'section_id' => 2,
            'abreviation' => 'Aucun',
            'nom' => 'Aucun',
        ),
        array(
            'id' => 24,
            'activite_type_id' => 3,
            'section_id' => 2,
            'abreviation' => 'Autre M/SSF',
            'nom' => 'Autre mandat SSF',
        ),
        array(
            'id' => 25,
            'activite_type_id' => 1,
            'section_id' => 1,
            'abreviation' => 'Autre F/SSC',
            'nom' => 'Autre fonction SSC',
        ),
        array(
            'id' => 26,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PO',
            'nom' => 'Professeur ordinaire',
        ),
        array(
            'id' => 27,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PO ad personam',
            'nom' => 'Professeur ordinaire ad personam',
        ),
        array(
            'id' => 28,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PAS',
            'nom' => 'Professeur associé',
        ),
        array(
            'id' => 29,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PAS ad personam',
            'nom' => 'Professeur associé ad personam',
        ),
        array(
            'id' => 30,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PAST',
            'nom' => 'Professeur assistant',
        ),
        array(
            'id' => 31,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PAST PTC',
            'nom' => 'Professeur assistant en prétitularisation conditionnelle',
        ),
        array(
            'id' => 32,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PAST boursier',
            'nom' => 'Professeur assistant boursier',
        ),
        array(
            'id' => 33,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PAST suppléant',
            'nom' => 'Professeur assistant suppléant',
        ),
        array(
            'id' => 34,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PTIT',
            'nom' => 'Professeur titulaire',
        ),
        array(
            'id' => 35,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PI avec indemnités',
            'nom' => 'Professeur invité avec indemnités',
        ),
        array(
            'id' => 36,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PI sans incidence financière',
            'nom' => 'Professeur invité sans incidence financière',
        ),
        array(
            'id' => 37,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PD-MER1',
            'nom' => 'Privat-docent et Maître d\'enseignement et de recherche, type 1',
        ),
        array(
            'id' => 38,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PD-MER2',
            'nom' => 'Privat-docent et Maître d\'enseignement et de recherche, type 2',
        ),
        array(
            'id' => 39,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PD',
            'nom' => 'Privat-docent',
        ),
        array(
            'id' => 40,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'PD sans incidence financière',
            'nom' => 'Privat-docent sans incidence financière',
        ),
        array(
            'id' => 41,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'MER1',
            'nom' => 'Maître d\'enseignement et de recherche, type 1',
        ),
        array(
            'id' => 42,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'MER2',
            'nom' => 'Maître d\'enseignement et de recherche, type 2',
        ),
        array(
            'id' => 43,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'CC avec indemnités',
            'nom' => 'Chargé de cours avec indemnités',
        ),
        array(
            'id' => 44,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'CC sans incidence financière',
            'nom' => 'Chargé de cours sans incidence financière',
        ),
        array(
            'id' => 45,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'MA',
            'nom' => 'Maître assistant',
        ),
        array(
            'id' => 46,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'MA suppléant',
            'nom' => 'Maître assistant suppléant',
        ),
        array(
            'id' => 47,
            'activite_type_id' => 2,
            'section_id' => 1,
            'abreviation' => 'Aucun',
            'nom' => 'Aucun',
        ),
        array(
            'id' => 48,
            'activite_type_id' => 3,
            'section_id' => 1,
            'abreviation' => 'Autre M/SSC',
            'nom' => 'Autre mandat SSC',
        ),
    ),
    'personne_type' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Enseignant'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Externe'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Etudiant'
        ),
    ),
    'commission_type' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Commission de présentation',
            'racine' => 'Présentation'
        ),
    ),
    'commission_fonction' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Président',
            'description' => 'Président de la commission',
            'position' => '1'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Expert extérieur',
            'description' => 'Expert extérieur',
            'position' => '7'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Délégué à l\'égalité',
            'description' => 'Délégué à l\'égalité',
            'position' => '8'
        ),
        array(
            'id' => '4',
            'actif' => '1',
            'nom' => 'Représentant du corps professoral',
            'description' => 'Représentant du corps professoral',
            'position' => '3'
        ),
        array(
            'id' => '5',
            'actif' => '1',
            'nom' => 'Représentant du corps intermédiaire',
            'description' => 'Représentant du corps intermédiaire',
            'position' => '4'
        ),
        array(
            'id' => '6',
            'actif' => '1',
            'nom' => 'Représentant des étudiants',
            'description' => 'Représentant des étudiants',
            'position' => '5'
        ),
        array(
            'id' => '7',
            'actif' => '1',
            'nom' => 'Représentant du Décanat',
            'description' => 'Représentant du Décanat',
            'position' => '2'
        ),
        array(
            'id' => '8',
            'actif' => '1',
            'nom' => 'Représentant de la DG CHUV',
            'description' => 'Représentant de la DG CHUV',
            'position' => '6'
        ),
        array(
            'id' => '9',
            'actif' => '1',
            'nom' => 'Invité',
            'description' => 'Invité',
            'position' => '9'
        ),
    ),
    'commission_etat' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'En cours',
            'description' => 'Commission en cours'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'En suspens',
            'description' => 'Commission en suspens'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Clôturé',
            'description' => 'Commission clôturée'
        ),
    ),
    'commission_travail_evenement_type' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'Séance: 1ère sélection sur dossiers'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'Journée: leçons, séminaires et visites'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Séance de délibération'
        ),
        array(
            'id' => '4',
            'actif' => '1',
            'nom' => 'Préparation séance'
        ),
        array(
            'id' => '5',
            'actif' => '1',
            'nom' => 'Rédaction du rapport'
        ),
    ),
    'commission_validation_etat' => array(
        array(
            'id' => '1',
            'actif' => '1',
            'nom' => 'En cours'
        ),
        array(
            'id' => '2',
            'actif' => '1',
            'nom' => 'En suspens'
        ),
        array(
            'id' => '3',
            'actif' => '1',
            'nom' => 'Clôturé'
        ),
    ),
);