[{name: 'id', type: 'int'},
{name: 'section', type: 'int'},
{name: 'date_retraite', type: 'date', dateFormat: 'Y-d-m'},
{name: 'personne_id', type: 'int'},
{name: 'personne_nom', type: 'string'},
{name: 'personne_prenom', type: 'string'},
{name: 'personne_adresse', type: 'string'},
{name: 'personne_pays_id', type: 'int'},
{name: 'personne_tel', type: 'string'},
{name: 'personne_date_naissance', type: 'date', dateFormat: 'Y-d-m'}]